travis:
  secure:
    BINSTAR_TOKEN: bvzaEKG5aDBNsncoQLKGPXbtX3jxNiEYUiGyJzo4nEjO02ff+9AI1tyMvk1rtNMLEksMjjTnwjbR1iRcVkyS1p8Z5scGxh7vp8jGB6E2AE54lHwKntAB/v32Qs80odQihU1a8OKWG+K0As3qGxzRCkWpZ+hTuggVmhkn0u75BBa2DksQW53uAGiucJ5MqyJtnnHqhrzCk69pgDldM7AqVYVflzmG/qRDePRcEz6yuI5NgzC5zajz+zSODpnGoo3cL4cAbo/csDX6Tbz87NzGaLU75QXMcN8WNQW0m8lllPqWJdQhPwN+tfD1LpcG8R/wuu/x1s52klMPzD8o57w7xBx8ojwMnWjkONaTGDq1P11HqAC/uxFtCaBe3GuYj2FrorYohjvn+RayWKb9vweExCPPUYQvYNh0j1MQYfsMM90eB1w/IrP5acgvCEuKD6oCcxzn3uW7vf759N4Oj2fnsypiDx2fpnB7dTig4al1vaZYFUXLkBUMjFajc5R097nQ2wW59fOl5m7y2v43F2Ix1zCjLcxyx+/eBaIAiyH+4oW2e1xxLskFxNJndWgqLCfFUSZaBfoxFzuiTA+pz0BpQY5NFhuvLav4ZRupC5M08ziwU2iRAZGo7fXr4PPc4HV9Y1NIIfF67kfOrf0TE0S3M+ApfWV+CXTIU7/FgtZ3Q00=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
