travis:
  secure:
    BINSTAR_TOKEN: APxnIE8XAwZoXYWYKL0ajYpBGwcqZ7tRUMosW9Du9GIdGgIRlk+kBJxythcK4F/RET4UBbT0MJV+1KNYcgVaXrD22t/zMqYTOFGkTNJL0coniyWXXepeek3RebHhH37cAQIFrqChs+l8mN/y9G2F9DuPo9hpA0mb00h4Nl5h2qV/qu+b9lnutIaLWRQcAeBukryhvChs0jqxNahINBD8ZHxaewC2xvcDjxzxV/WFJBBn/kvA7/2cmUnoByQdXJHxjtnW4AZUFkeHjyHnA0UOMnTZJmZlia6JS3EHKKrihKxUPw1o/yLwjnPvnTTyr0glh9gcS5Q170a8rmJI76WjK0q+J35hQ4gOAUZTzrK+7Va1JhI1IdTz8c0pIpsUOXoiJ6vt8b5I0bcZ3KUgorrGjyZtZb8GqyNK9hGNiY19x5SZo0ffkGdSxGFg2J539SCHR61yhx6vdrzB1mIxT/Pg21rSirVPTKyaXPwFbd4L32iWm4CIUQSdvKRbxCtrttY1kDbL1Lubm7lPM2sXjePqZ9rK0PuC1pS87F58AM3DKTAYZK4dOYL0TB2DWgJjyN3rMQudT7dixC/7a7LK7KsPpqeOCzzHq02Hg3iC/icxIlIvkyWjxbhpdFNMaW0vuVQFLHeMWz45gzM74hI5wdNFRdSUGrZD0Yf86udnmcTr1Pc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
